use_small_heuristics = "Max"
combine_control_expr = false
fn_single_line = true
merge_imports = true
use_try_shorthand = true
wrap_comments = true
blank_lines_upper_bound=2
unstable_features = true
edition = "2018"
imports_layout = "Mixed"
condense_wildcard_suffixes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
use_field_init_shorthand = true
trailing_semicolon = false